### ISSUE TITLE
Address flag toss resets

### ISSUE THREAD

**Issue by JeffBobbo** [red-eclipse/base#321]
http://redeclipse.net/forum/viewtopic.php?f=4&t=725

**Comment by shirepirate** [comment]
this has already been addressed with a 30-second penalty when dumping a flag, in which you cannot touch your own flag. if you're proposing a better solution you need to present it clearly so it can be implemented or denied, a link to a gridlocked forum discussion is not nearly adequate.

**Comment by qreeves** [comment]
It's okay, I asked for this issue to be created as a reminder for me. It is something I will have to experiment with to find a solution that works.

**Comment by shirepirate** [comment]
a solution equivalent to penalty cards in soccer might work, with 3 of such actions resulting in a point loss for the team. obviously this would need to be very clear in communication when it happens, like a large message across the screen and perhaps flashing a certain color.

this would also instill the idea that dumping your flag in practice is a bad thing, and will lose the game for you.

**Comment by shirepirate** [comment]
could try this in 1.5.5 to see if it works: have the flag spawn on a new type of entity carefully placed per team in the center area of the map (not using the similar king dac algorithm, which might be prone to calculation error and wouldn't work well when both flags need to spawn in the center).

this would require placing some new entites in every capture map, though. not really that large of an undertaking once the functionality is there.

then, if a player dies holding their own flag it will spawn in this new central entity for the taking, just as it would in the base normally. players could pick it up if it was their own team flag and restore it to their base if necessary.

what do you know, this also discourages flag camping on several maps (fall and die or get pushed off and your flag ends up in the center instead of your base).

this would also need to go along with removing all timers pertaining to teams touching their own flag, including when returning 1 flag or both flags to a base (is that a separate bug that deserves another issue?)

**Comment by JeffBobbo** [comment]
This (or a very similar system) was suggested in the original forum topic and wouldn't work. You still have the same problems, just flags will respawn in different places. This would still allow people to flag toss their flag from the enemy base (which is the first major issue) and still allows for the troll-style play of securing the flag to toss it after luring a player away (and thus away from where ever the flag is going to be). True, it'd alleviate it a little, but not enough to be worth while (as the system would still need fixing).

> this would also need to go along with removing all timers pertaining to teams touching their own flag, including when returning 1 flag or both flags to a base (is that a separate bug that deserves another issue?)
I don't think this is a bug, but should probably be considered as such, I've not seen these timers cause anything but confusion and frustration.

**Comment by shirepirate** [comment]
i don't see any better solution, if it makes the game more fair and alleviates some of the balance issues than it is worthwhile implementing. @qreeves will be able to clue in on how complicated it is to change to this style of flag respawning.

having the flag float or warp back to solid ground is not a good solution, i can safely say this will be universally hated and it doesn't make a lot of sense. it might be more complex to code as well.

it's woth trying this to see how it plays out in my opinion.

**Comment by JeffBobbo** [comment]
> having the flag float or warp back to solid ground is not a good solution

Why not?

> i can safely say this will be universally hated

Because?

> it doesn't make a lot of sense

Hence suggesting replacing flags with drones, plus drones look more sci-fi cool and can be smaller (and thus obstruct your view less for 3p players).


Rereading the forum topic, the overall consensus seems to be to move the flag to place where it was last being held by a person on the ground (which @qreeves likes the idea of), which isn't too dissimilar to my suggestion (the other parts I suggested are still required, the only difference really is using last position instead of nearest waypoint).

**Comment by shirepirate** [comment]
i really have no intention of getting into it with a dogmatist, but i'll give a few thoughts on it (i think these are more straightforward facts though, not really just my opinion):

having a flag or drone or whatever spawn in an undetermined spot (one which will almost never be known for certain at the moment it happens) is inherently more confusing than having it spawn in a specific location

having it spawn in a location it was last held will very often result in someone picking it up unwittingly (yes, there are measures we are also going to take before the next release to alleviate this confusion more, but it will still very likely happen often)

changing the flag to something other than a flag will be met with irritation by a fair amount of the user base, simply for the fact that it is different alone (but in addition, the movement mechanics that might come with a different form also). not to mention why players need to navigate active drones in the first place, the flag is presumably an inanimate object.

it is a risk to change something that is better than good into something that may be very bad. a good percentage of our player base only enjoy the Capture-the-Flag mode, and fucking with it too much could worse case scenario lead to them no longer playing the game.

those reasons aside i've never been against flag tossing, and am not pretending to hide that bias, however recently it has become more of a problem when a game is already very unbalanced. it's definitely worth noting this will be quite different when the balance mechanic is changed again to incorporate statistics though. I still agree that some change should be made, as it's a rather cheap tactic. the halfway spawn is a good compromise to a bad situation, and much safer than creating a worse situation.

i know you will try to pontificate whether you have a solid argument against these points or not, but that is all i'll say on this matter, so let others vote and decide on what should be done about the issue. if players need to be polled about it it would probably be better to let @qreeves create it, or simply let him choose what he thinks is best.

**Comment by acerspyro** [comment]
(Psst... Make it a holographic flag!)

**Comment by qreeves** [comment]
Yeah, the ultimate decision will have to be left up to me. I'm still mulling over the idea in my head.

**Comment by bonifarz** [comment]
> flag resets to specify a position which is set to the carrier's last floor position

That's cool, and it works like a charm.
